/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.google.android.systemui.power;

import com.android.internal.logging.UiEventLogger;

public enum BatteryMetricEvent implements UiEventLogger.UiEventEnum {
    BATTERY_DEFENDER_NOTIFICATION(876),
    BATTERY_DEFENDER_BYPASS_LIMIT(877),
    BATTERY_DEFENDER_BYPASS_LIMIT_FOR_TIPS(878),
    DELETE_BATTERY_DEFENDER_NOTIFICATION(1273),
    ADAPTIVE_CHARGING_NOTIFICATION(1274),
    DELETE_ADAPTIVE_CHARGING_NOTIFICATION(1275),
    ADAPTIVE_CHARGING_NOTIFICATION_BYPASS(1346),
    SEND_INCOMPATIBLE_CHARGING_NOTIFICATION(1271),
    DELETE_INCOMPATIBLE_CHARGING_NOTIFICATION(1272),
    SEND_WIRELESS_CHARGING_NOTIFICATION(1614),
    DISMISS_WIRELESS_CHARGING_NOTIFICATION(1615),
    DISABLE_WIRELESS_CHARGING_NOTIFICATION(1616),
    SEVERE_BATTERY_DIALOG(991),
    SEVERE_BATTERY_DIALOG_TURN_ON(992),
    SEVERE_BATTERY_DIALOG_CANCEL(993),
    SEVERE_BATTERY_DIALOG_DISMISS_EVENT(994),
    SAVER_CONFIRMATION_DIALOG(1347),
    SAVER_CONFIRMATION_DIALOG_TURN_ON(1348),
    SAVER_CONFIRMATION_DIALOG_CANCEL(1349),
    SAVER_CONFIRMATION_DIALOG_SETUP(1350),
    EXTREME_LOW_BATTERY_NOTIFICATION(1351),
    BATTERY_SAVER_ENABLED(1359),
    BATTERY_SAVER_ENABLED_REASON(1360),
    BATTERY_SAVER_DISABLED(1372),
    BATTERY_SAVER_DISABLED_REASON(1373),
    SEND_CHARGE_LIMIT_DISCOVERY_NOTIFICATION(1707),
    DISMISS_CHARGE_LIMIT_DISCOVERY_NOTIFICATION(1708),
    ENABLE_CHARGE_LIMIT_FEATURE(1709),
    CLICK_CHARGE_LIMIT_DISCOVERY_NOTIFICATION(1712),
    CLICK_WIRELESS_CHARGING_NOTIFICATION(1713),
    SEVERE_LOW_BATTERY_NOTIFICATION_TURN_ON_EBS(1834),
    SEVERE_LOW_BATTERY_NOTIFICATION_SWITCH_TO_EBS(1835),
    SEVERE_LOW_BATTERY_NOTIFICATION_TURN_ON_EBS_CLICK_TURN_ON(1836),
    SEVERE_LOW_BATTERY_NOTIFICATION_SWITCH_TO_EBS_CLICK_SWITCH(1837),
    SEVERE_LOW_BATTERY_NOTIFICATION_TURN_ON_EBS_DISMISS(1838),
    SEVERE_LOW_BATTERY_NOTIFICATION_SWITCH_TO_EBS_DISMISS(1839),
    SEND_PULSAR_ENABLED_NOTIFICATION(2189),
    DISMISS_PULSAR_ENABLED_NOTIFICATION(2190),
    CLICK_PULSAR_ENABLED_NOTIFICATION(2191),
    SEND_PULSAR_REMINDER_NOTIFICATION(2207),
    DISMISS_PULSAR_REMINDER_NOTIFICATION(2208),
    CLICK_PULSAR_REMINDER_NOTIFICATION(2209),
    SHOW_SHUTDOWN_MODE_SCREEN(2222),
    DISMISS_SHUTDOWN_MODE_SCREEN(2223),
    CLICK_SHUTDOWN_MODE_SCREEN_SHUTDOWN_BUTTON(2224),
    CLICK_SHUTDOWN_MODE_CONFIRM_DIALOG_SHUTDOWN_BUTTON(2225),
    SHOW_POST_SHUTDOWN_MODE_DIALOG(2226),
    RECOVER_SHUTDOWN_MODE(2227),
    CHECK_SHUTDOWN_MODE_STATE(2228);

    private final int mId;

    BatteryMetricEvent(int id) {
        mId = id;
    }

    @Override
    public int getId() {
        return mId;
    }
}
